# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 811)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 4, 0, 1, 3)
        self.takeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.takeButton.setObjectName("takeButton")
        self.gridLayout.addWidget(self.takeButton, 3, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.takeInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.takeInput.setObjectName("takeInput")
        self.gridLayout.addWidget(self.takeInput, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.stones = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.stones.setObjectName("stones")
        self.gridLayout.addWidget(self.stones, 0, 1, 1, 1)
        self.remainLcd = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.remainLcd.setObjectName("remainLcd")
        self.gridLayout.addWidget(self.remainLcd, 1, 0, 1, 3)
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 2, 1, 1)
        self.resultLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        self.gridLayout.addWidget(self.resultLabel, 5, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.takeButton.setText(_translate("MainWindow", "Взять"))
        self.label_2.setText(_translate("MainWindow", "Сколь камней взять?"))
        self.label.setText(_translate("MainWindow", "Задать количество камней"))
        self.startButton.setText(_translate("MainWindow", "Задать"))
